In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
input_df = pd.read_csv('.\churnData\All_Base_Churn_Report_2.0_2022_01_10.csv')
last_month_details = pd.read_csv('.\churnData\All_last_month_details_2021_12_16.csv')

In [3]:
input_df

,uid,region,meses_activo,subtotal,segmento,phone,tipo,razon,detalle,otros_productos,lugares_mejor_precio,comercial
0,-269877,CMX,24,58.532048,Restaurante,NaN,NaN,NaN,NaN,NaN,NaN,Pepito Perez
1,-269778,CMX,18,25.513288,Comercio,NaN,NaN,NaN,NaN,NaN,NaN,Juan Ignacio PercovichBAJA
2,-269776,CMX,28,57.279833,Restaurante,NaN,NaN,NaN,NaN,NaN,NaN,Cliente Graduado
3,-269702,CMX,24,96.856696,Comercio,NaN,NaN,NaN,NaN,NaN,NaN,Juan Ignacio PercovichBAJA
4,-269615,CMX,29,336.969255,Restaurante,NaN,NaN,NaN,NaN,NaN,NaN,Cliente Graduado
...,...,...,...,...,...,...,...,...,...,...,...,...
11184,80662015,CMX,0,90.340803,Restaurante,NaN,NaN,NaN,NaN,NaN,NaN,Tomas Esparza Martínez
11185,80662892,CMX,0,32.341845,Restaurante,NaN,NaN,NaN,NaN,NaN,NaN,Elena Mendez RuizBAJA
11186,80668187,PBC,0,23.055758,Restaurante,NaN,NaN,NaN,NaN,NaN,NaN,RICARDO ZURIEL HERNANDEZ
11187,80675750,CMX,0,33.350703,Restaurante,NaN,NaN,NaN,NaN,NaN,NaN,CARLOS JAVIER JUAREZ LOPEZ
11188,80691542,CMX,1,163.893695,Restaurante,NaN,NaN,NaN,NaN,NaN,NaN,OSCAR IVAN PEREZ RAMIREZ

In [4]:
#Delete Duplicates
input_df.drop_duplicates(subset=['uid'], keep='last', inplace=True)

In [5]:
#replace na por Sin motivo
input_df.fillna(value= {'razon':'sin motivo'}, inplace=True)

In [6]:
input_df

,uid,region,meses_activo,subtotal,segmento,phone,tipo,razon,detalle,otros_productos,lugares_mejor_precio,comercial
0,-269877,CMX,24,58.532048,Restaurante,NaN,NaN,sin motivo,NaN,NaN,NaN,Pepito Perez
1,-269778,CMX,18,25.513288,Comercio,NaN,NaN,sin motivo,NaN,NaN,NaN,Juan Ignacio PercovichBAJA
2,-269776,CMX,28,57.279833,Restaurante,NaN,NaN,sin motivo,NaN,NaN,NaN,Cliente Graduado
3,-269702,CMX,24,96.856696,Comercio,NaN,NaN,sin motivo,NaN,NaN,NaN,Juan Ignacio PercovichBAJA
4,-269615,CMX,29,336.969255,Restaurante,NaN,NaN,sin motivo,NaN,NaN,NaN,Cliente Graduado
...,...,...,...,...,...,...,...,...,...,...,...,...
11184,80662015,CMX,0,90.340803,Restaurante,NaN,NaN,sin motivo,NaN,NaN,NaN,Tomas Esparza Martínez
11185,80662892,CMX,0,32.341845,Restaurante,NaN,NaN,sin motivo,NaN,NaN,NaN,Elena Mendez RuizBAJA
11186,80668187,PBC,0,23.055758,Restaurante,NaN,NaN,sin motivo,NaN,NaN,NaN,RICARDO ZURIEL HERNANDEZ
11187,80675750,CMX,0,33.350703,Restaurante,NaN,NaN,sin motivo,NaN,NaN,NaN,CARLOS JAVIER JUAREZ LOPEZ
11188,80691542,CMX,1,163.893695,Restaurante,NaN,NaN,sin motivo,NaN,NaN,NaN,OSCAR IVAN PEREZ RAMIREZ

In [7]:
#Define term of users long-short
input_df.loc[:,['term']] = input_df.apply(lambda x: 'long' if x['meses_activo']>3 else 'short', axis=1)

In [8]:
#razones
razones = pd.DataFrame({'razon': input_df['razon'].unique(), 'long':0, 'short':0})

In [9]:
global_terms = pd.pivot_table(input_df, values='uid', index=['razon'], columns=['term'], aggfunc='count').reset_index()
global_terms = pd.concat([global_terms, razones]).groupby('razon').sum().reset_index()
global_terms = global_terms[global_terms['razon'] != 'sin motivo']
global_terms['%_long'] = global_terms['long']/global_terms['long'].sum()* 100
global_terms['%_short'] = global_terms['short']/global_terms['short'].sum() * 100
global_terms[['razon','long', '%_long', 'short', '%_short']]

,razon,long,%_long,short,%_short
0,Actualmente compra al día,92.0,18.661258,132.0,20.886076
1,Contaminado / Descompuesto (Podrido),6.0,1.217039,5.0,0.791139
2,Creo una cuenta nueva,6.0,1.217039,4.0,0.632911
3,Descuento o promoción no aplicado / mal calculado,1.0,0.202840,4.0,0.632911
4,El horario de entrega de la mañana es muy útil...,1.0,0.202840,0.0,0.000000
5,Eles entregaram fora do horário,0.0,0.000000,2.0,0.316456
6,Faixas de entrega não funcionam para mim,0.0,0.000000,3.0,0.474684
7,Golpeado,1.0,0.202840,4.0,0.632911
8,Maduración incorrecta (verde o sobremaduro),1.0,0.202840,8.0,1.265823
9,Mala atención del conductor,6.0,1.217039,10.0,1.582278
10,Mala atención del hunter,1.0,0.202840,5.0,0.791139
11,Me entregaron producto equivocado,1.0,0.202840,3.0,0.474684
12,Necesita de credito,56.0,11.359026,64.0,10.126582
13,No sabe usar la app,0.0,0.000000,3.0,0.474684
14,Orden no llega a pedido mínimo,160.0,32.454361,185.0,29.272152
15,Parte de mi pedido no llegó,7.0,1.419878,5.0,0.791139
16,Pedido nunca llegó,3.0,0.608519,5.0,0.791139
17,Precios no competitivos,72.0,14.604462,100.0,15.822785
18,Prefiero una hora de entrega especifica,4.0,0.811359,5.0,0.791139
19,Problema con Boleto,4.0,0.811359,4.0,0.632911
20,Problema con app Frubana,10.0,2.028398,7.0,1.107595
21,Productos Agotados,17.0,3.448276,16.0,2.531646
22,Servicio al cliente,18.0,3.651116,22.0,3.481013
23,Tamaño erróneo (pequeño o grande),4.0,0.811359,6.0,0.949367
24,Tuvo un problema y no lo supo reportar,22.0,4.462475,30.0,4.746835

In [10]:
def term_analysis_region(df, region=''):
    """Return the dataframe specified by each reasons for long and short term user"""
    
    reasons = pd.DataFrame({'razon': input_df['razon'].unique(), 'long':0, 'short':0})
    if region:
        df = df[df['region']==region]
        
    term_df = pd.pivot_table(df, values='uid', index=['razon'], columns=['term'], aggfunc='count').reset_index()
    term_df = pd.concat([term_df, reasons]).groupby('razon').sum().reset_index()
    term_df = term_df[term_df['razon'] != 'sin motivo']
    term_df['%_long'] = term_df['long']/term_df['long'].sum()* 100
    term_df['%_short'] = term_df['short']/term_df['short'].sum() * 100
    term_df.fillna(0, inplace=True)
    return term_df[['razon','long', '%_long', 'short', '%_short']]

In [11]:
term_analysis_region(input_df)

,razon,long,%_long,short,%_short
0,Actualmente compra al día,92.0,18.661258,132.0,20.886076
1,Contaminado / Descompuesto (Podrido),6.0,1.217039,5.0,0.791139
2,Creo una cuenta nueva,6.0,1.217039,4.0,0.632911
3,Descuento o promoción no aplicado / mal calculado,1.0,0.202840,4.0,0.632911
4,El horario de entrega de la mañana es muy útil...,1.0,0.202840,0.0,0.000000
5,Eles entregaram fora do horário,0.0,0.000000,2.0,0.316456
6,Faixas de entrega não funcionam para mim,0.0,0.000000,3.0,0.474684
7,Golpeado,1.0,0.202840,4.0,0.632911
8,Maduración incorrecta (verde o sobremaduro),1.0,0.202840,8.0,1.265823
9,Mala atención del conductor,6.0,1.217039,10.0,1.582278
10,Mala atención del hunter,1.0,0.202840,5.0,0.791139
11,Me entregaron producto equivocado,1.0,0.202840,3.0,0.474684
12,Necesita de credito,56.0,11.359026,64.0,10.126582
13,No sabe usar la app,0.0,0.000000,3.0,0.474684
14,Orden no llega a pedido mínimo,160.0,32.454361,185.0,29.272152
15,Parte de mi pedido no llegó,7.0,1.419878,5.0,0.791139
16,Pedido nunca llegó,3.0,0.608519,5.0,0.791139
17,Precios no competitivos,72.0,14.604462,100.0,15.822785
18,Prefiero una hora de entrega especifica,4.0,0.811359,5.0,0.791139
19,Problema con Boleto,4.0,0.811359,4.0,0.632911
20,Problema con app Frubana,10.0,2.028398,7.0,1.107595
21,Productos Agotados,17.0,3.448276,16.0,2.531646
22,Servicio al cliente,18.0,3.651116,22.0,3.481013
23,Tamaño erróneo (pequeño o grande),4.0,0.811359,6.0,0.949367
24,Tuvo un problema y no lo supo reportar,22.0,4.462475,30.0,4.746835

In [12]:
cities = ['BOG', 'BAQ', 'CMX', 'GDL', 'SPO', 'BHZ']

In [13]:
term_analysis_region(input_df, 'BOG')

,razon,long,%_long,short,%_short
0,Actualmente compra al día,20.0,25.974026,27.0,27.551020
1,Contaminado / Descompuesto (Podrido),2.0,2.597403,1.0,1.020408
2,Creo una cuenta nueva,1.0,1.298701,0.0,0.000000
3,Descuento o promoción no aplicado / mal calculado,0.0,0.000000,3.0,3.061224
4,El horario de entrega de la mañana es muy útil...,0.0,0.000000,0.0,0.000000
5,Eles entregaram fora do horário,0.0,0.000000,0.0,0.000000
6,Faixas de entrega não funcionam para mim,0.0,0.000000,0.0,0.000000
7,Golpeado,1.0,1.298701,1.0,1.020408
8,Maduración incorrecta (verde o sobremaduro),0.0,0.000000,2.0,2.040816
9,Mala atención del conductor,2.0,2.597403,1.0,1.020408
10,Mala atención del hunter,0.0,0.000000,2.0,2.040816
11,Me entregaron producto equivocado,0.0,0.000000,1.0,1.020408
12,Necesita de credito,0.0,0.000000,0.0,0.000000
13,No sabe usar la app,0.0,0.000000,0.0,0.000000
14,Orden no llega a pedido mínimo,7.0,9.090909,4.0,4.081633
15,Parte de mi pedido no llegó,3.0,3.896104,0.0,0.000000
16,Pedido nunca llegó,0.0,0.000000,1.0,1.020408
17,Precios no competitivos,27.0,35.064935,34.0,34.693878
18,Prefiero una hora de entrega especifica,1.0,1.298701,0.0,0.000000
19,Problema con Boleto,0.0,0.000000,0.0,0.000000
20,Problema con app Frubana,4.0,5.194805,4.0,4.081633
21,Productos Agotados,3.0,3.896104,2.0,2.040816
22,Servicio al cliente,5.0,6.493506,11.0,11.224490
23,Tamaño erróneo (pequeño o grande),0.0,0.000000,3.0,3.061224
24,Tuvo un problema y no lo supo reportar,1.0,1.298701,1.0,1.020408

In [14]:
term_analysis_region(input_df, 'BAQ')

,razon,long,%_long,short,%_short
0,Actualmente compra al día,0.0,0.0,0.0,0.0
1,Contaminado / Descompuesto (Podrido),0.0,0.0,0.0,0.0
2,Creo una cuenta nueva,0.0,0.0,0.0,0.0
3,Descuento o promoción no aplicado / mal calculado,0.0,0.0,0.0,0.0
4,El horario de entrega de la mañana es muy útil...,0.0,0.0,0.0,0.0
5,Eles entregaram fora do horário,0.0,0.0,0.0,0.0
6,Faixas de entrega não funcionam para mim,0.0,0.0,0.0,0.0
7,Golpeado,0.0,0.0,0.0,0.0
8,Maduración incorrecta (verde o sobremaduro),0.0,0.0,0.0,0.0
9,Mala atención del conductor,0.0,0.0,0.0,0.0
10,Mala atención del hunter,0.0,0.0,0.0,0.0
11,Me entregaron producto equivocado,0.0,0.0,0.0,0.0
12,Necesita de credito,0.0,0.0,0.0,0.0
13,No sabe usar la app,0.0,0.0,0.0,0.0
14,Orden no llega a pedido mínimo,0.0,0.0,0.0,0.0
15,Parte de mi pedido no llegó,0.0,0.0,0.0,0.0
16,Pedido nunca llegó,0.0,0.0,0.0,0.0
17,Precios no competitivos,1.0,100.0,0.0,0.0
18,Prefiero una hora de entrega especifica,0.0,0.0,0.0,0.0
19,Problema con Boleto,0.0,0.0,0.0,0.0
20,Problema con app Frubana,0.0,0.0,0.0,0.0
21,Productos Agotados,0.0,0.0,0.0,0.0
22,Servicio al cliente,0.0,0.0,0.0,0.0
23,Tamaño erróneo (pequeño o grande),0.0,0.0,0.0,0.0
24,Tuvo un problema y no lo supo reportar,0.0,0.0,0.0,0.0

In [15]:
term_analysis_region(input_df, 'CMX')

,razon,long,%_long,short,%_short
0,Actualmente compra al día,0.0,0.000000,0.0,0.000000
1,Contaminado / Descompuesto (Podrido),3.0,1.515152,2.0,1.092896
2,Creo una cuenta nueva,4.0,2.020202,2.0,1.092896
3,Descuento o promoción no aplicado / mal calculado,1.0,0.505051,1.0,0.546448
4,El horario de entrega de la mañana es muy útil...,1.0,0.505051,0.0,0.000000
5,Eles entregaram fora do horário,0.0,0.000000,0.0,0.000000
6,Faixas de entrega não funcionam para mim,0.0,0.000000,0.0,0.000000
7,Golpeado,0.0,0.000000,0.0,0.000000
8,Maduración incorrecta (verde o sobremaduro),0.0,0.000000,4.0,2.185792
9,Mala atención del conductor,4.0,2.020202,6.0,3.278689
10,Mala atención del hunter,0.0,0.000000,2.0,1.092896
11,Me entregaron producto equivocado,0.0,0.000000,0.0,0.000000
12,Necesita de credito,8.0,4.040404,7.0,3.825137
13,No sabe usar la app,0.0,0.000000,0.0,0.000000
14,Orden no llega a pedido mínimo,98.0,49.494949,103.0,56.284153
15,Parte de mi pedido no llegó,4.0,2.020202,3.0,1.639344
16,Pedido nunca llegó,3.0,1.515152,3.0,1.639344
17,Precios no competitivos,28.0,14.141414,16.0,8.743169
18,Prefiero una hora de entrega especifica,3.0,1.515152,4.0,2.185792
19,Problema con Boleto,0.0,0.000000,0.0,0.000000
20,Problema con app Frubana,1.0,0.505051,0.0,0.000000
21,Productos Agotados,11.0,5.555556,7.0,3.825137
22,Servicio al cliente,7.0,3.535354,5.0,2.732240
23,Tamaño erróneo (pequeño o grande),4.0,2.020202,2.0,1.092896
24,Tuvo un problema y no lo supo reportar,18.0,9.090909,16.0,8.743169

In [16]:
term_analysis_region(input_df, 'GDL')

,razon,long,%_long,short,%_short
0,Actualmente compra al día,0.0,0.000000,0.0,0.000000
1,Contaminado / Descompuesto (Podrido),0.0,0.000000,2.0,3.030303
2,Creo una cuenta nueva,0.0,0.000000,1.0,1.515152
3,Descuento o promoción no aplicado / mal calculado,0.0,0.000000,0.0,0.000000
4,El horario de entrega de la mañana es muy útil...,0.0,0.000000,0.0,0.000000
5,Eles entregaram fora do horário,0.0,0.000000,0.0,0.000000
6,Faixas de entrega não funcionam para mim,0.0,0.000000,0.0,0.000000
7,Golpeado,0.0,0.000000,2.0,3.030303
8,Maduración incorrecta (verde o sobremaduro),0.0,0.000000,0.0,0.000000
9,Mala atención del conductor,0.0,0.000000,0.0,0.000000
10,Mala atención del hunter,0.0,0.000000,0.0,0.000000
11,Me entregaron producto equivocado,0.0,0.000000,0.0,0.000000
12,Necesita de credito,2.0,22.222222,4.0,6.060606
13,No sabe usar la app,0.0,0.000000,3.0,4.545455
14,Orden no llega a pedido mínimo,3.0,33.333333,19.0,28.787879
15,Parte de mi pedido no llegó,0.0,0.000000,2.0,3.030303
16,Pedido nunca llegó,0.0,0.000000,1.0,1.515152
17,Precios no competitivos,1.0,11.111111,16.0,24.242424
18,Prefiero una hora de entrega especifica,0.0,0.000000,1.0,1.515152
19,Problema con Boleto,0.0,0.000000,0.0,0.000000
20,Problema con app Frubana,0.0,0.000000,2.0,3.030303
21,Productos Agotados,1.0,11.111111,7.0,10.606061
22,Servicio al cliente,1.0,11.111111,2.0,3.030303
23,Tamaño erróneo (pequeño o grande),0.0,0.000000,1.0,1.515152
24,Tuvo un problema y no lo supo reportar,1.0,11.111111,3.0,4.545455

In [17]:
term_analysis_region(input_df, 'SPO')

,razon,long,%_long,short,%_short
0,Actualmente compra al día,72.0,34.615385,102.0,36.170213
1,Contaminado / Descompuesto (Podrido),1.0,0.480769,0.0,0.000000
2,Creo una cuenta nueva,1.0,0.480769,1.0,0.354610
3,Descuento o promoción no aplicado / mal calculado,0.0,0.000000,0.0,0.000000
4,El horario de entrega de la mañana es muy útil...,0.0,0.000000,0.0,0.000000
5,Eles entregaram fora do horário,0.0,0.000000,2.0,0.709220
6,Faixas de entrega não funcionam para mim,0.0,0.000000,3.0,1.063830
7,Golpeado,0.0,0.000000,1.0,0.354610
8,Maduración incorrecta (verde o sobremaduro),1.0,0.480769,2.0,0.709220
9,Mala atención del conductor,0.0,0.000000,3.0,1.063830
10,Mala atención del hunter,1.0,0.480769,1.0,0.354610
11,Me entregaron producto equivocado,1.0,0.480769,2.0,0.709220
12,Necesita de credito,46.0,22.115385,53.0,18.794326
13,No sabe usar la app,0.0,0.000000,0.0,0.000000
14,Orden no llega a pedido mínimo,52.0,25.000000,59.0,20.921986
15,Parte de mi pedido no llegó,0.0,0.000000,0.0,0.000000
16,Pedido nunca llegó,0.0,0.000000,0.0,0.000000
17,Precios no competitivos,15.0,7.211538,34.0,12.056738
18,Prefiero una hora de entrega especifica,0.0,0.000000,0.0,0.000000
19,Problema con Boleto,4.0,1.923077,4.0,1.418440
20,Problema con app Frubana,5.0,2.403846,1.0,0.354610
21,Productos Agotados,2.0,0.961538,0.0,0.000000
22,Servicio al cliente,5.0,2.403846,4.0,1.418440
23,Tamaño erróneo (pequeño o grande),0.0,0.000000,0.0,0.000000
24,Tuvo un problema y no lo supo reportar,2.0,0.961538,10.0,3.546099

In [18]:
term_analysis_region(input_df, 'BHZ')

,razon,long,%_long,short,%_short
0,Actualmente compra al día,0.0,0.0,3,100.0
1,Contaminado / Descompuesto (Podrido),0.0,0.0,0,0.0
2,Creo una cuenta nueva,0.0,0.0,0,0.0
3,Descuento o promoción no aplicado / mal calculado,0.0,0.0,0,0.0
4,El horario de entrega de la mañana es muy útil...,0.0,0.0,0,0.0
5,Eles entregaram fora do horário,0.0,0.0,0,0.0
6,Faixas de entrega não funcionam para mim,0.0,0.0,0,0.0
7,Golpeado,0.0,0.0,0,0.0
8,Maduración incorrecta (verde o sobremaduro),0.0,0.0,0,0.0
9,Mala atención del conductor,0.0,0.0,0,0.0
10,Mala atención del hunter,0.0,0.0,0,0.0
11,Me entregaron producto equivocado,0.0,0.0,0,0.0
12,Necesita de credito,0.0,0.0,0,0.0
13,No sabe usar la app,0.0,0.0,0,0.0
14,Orden no llega a pedido mínimo,0.0,0.0,0,0.0
15,Parte de mi pedido no llegó,0.0,0.0,0,0.0
16,Pedido nunca llegó,0.0,0.0,0,0.0
17,Precios no competitivos,0.0,0.0,0,0.0
18,Prefiero una hora de entrega especifica,0.0,0.0,0,0.0
19,Problema con Boleto,0.0,0.0,0,0.0
20,Problema con app Frubana,0.0,0.0,0,0.0
21,Productos Agotados,0.0,0.0,0,0.0
22,Servicio al cliente,0.0,0.0,0,0.0
23,Tamaño erróneo (pequeño o grande),0.0,0.0,0,0.0
24,Tuvo un problema y no lo supo reportar,0.0,0.0,0,0.0

In [19]:
present = input_df.groupby(['segmento'])['uid'].count().reset_index()

In [20]:
past = last_month_details.groupby(['segmento'])['uid'].count().reset_index().rename(columns={'segmento':'segmento_past', 'uid':'uid_past'})

In [21]:
segment = pd.concat([present, past], axis=1)[['segmento', 'uid', 'uid_past']]
segment = segment.append(segment.sum(numeric_only=True), ignore_index=True)
segment['%'] = segment['uid']/segment['uid_past'] * 100
segment['segmento'].fillna('Total', inplace=True)

In [22]:
segment

        segmento      uid  uid_past          %
0  CNPJ Invalido     44.0      54.0  81.481481
1       Comercio   1734.0    5484.0  31.619256
2    Institución     71.0     213.0  33.333333
3    Restaurante   8826.0   52880.0  16.690620
4          Total  10675.0   58631.0  18.207092

In [23]:
def segment_analysis(present_df, past_df, city=''):
    if city:
        present_df = present_df[present_df['region']==city]
        past_df = past_df[past_df['region']==city]
    
    present_resume = present_df.groupby(['segmento'])['uid'].count().reset_index()
    past_resume =  past_df.groupby(['segmento']).count().reset_index().rename(columns={'segmento':'segmento_past', 'uid':'uid_past'})
    
    result = pd.concat([present_resume, past_resume], axis=1)[['segmento', 'uid', 'uid_past']]
    result = result.append(result.sum(numeric_only=True), ignore_index=True)
    result['%'] = result['uid']/result['uid_past'] * 100
    result['segmento'].fillna('Total', inplace=True)
    return  result

In [24]:
segment_analysis(input_df, last_month_details)

        segmento      uid  uid_past          %
0  CNPJ Invalido     44.0      54.0  81.481481
1       Comercio   1734.0    5484.0  31.619256
2    Institución     71.0     213.0  33.333333
3    Restaurante   8826.0   52880.0  16.690620
4          Total  10675.0   58631.0  18.207092

In [25]:
segment_analysis(input_df, last_month_details, 'BOG')

      segmento     uid  uid_past          %
0     Comercio   298.0     602.0  49.501661
1  Institución    26.0      58.0  44.827586
2  Restaurante  2154.0   15906.0  13.542060
3        Total  2478.0   16566.0  14.958348

In [26]:
segment_analysis(input_df, last_month_details, 'BAQ')

      segmento    uid  uid_past          %
0     Comercio  335.0    2306.0  14.527320
1  Institución   10.0      25.0  40.000000
2  Restaurante  313.0    2707.0  11.562615
3        Total  658.0    5038.0  13.060738

In [27]:
segment_analysis(input_df, last_month_details, 'CMX')

      segmento     uid  uid_past          %
0     Comercio   670.0    1661.0  40.337146
1  Institución     8.0      44.0  18.181818
2  Restaurante  3008.0   14131.0  21.286533
3        Total  3686.0   15836.0  23.276080

In [28]:
segment_analysis(input_df, last_month_details, 'GDL')

      segmento    uid  uid_past          %
0     Comercio  162.0     311.0  52.090032
1  Institución   11.0      17.0  64.705882
2  Restaurante  539.0    2919.0  18.465228
3        Total  712.0    3247.0  21.927933

In [29]:
segment_analysis(input_df, last_month_details, 'SPO')

        segmento     uid  uid_past          %
0  CNPJ Invalido    29.0      38.0  76.315789
1       Comercio   224.0     536.0  41.791045
2    Institución    13.0      65.0  20.000000
3    Restaurante  2504.0   15771.0  15.877243
4          Total  2770.0   16410.0  16.879951

In [30]:
segment_analysis(input_df, last_month_details, 'BHZ')

        segmento    uid  uid_past           %
0  CNPJ Invalido   15.0      16.0   93.750000
1       Comercio    8.0      10.0   80.000000
2    Institución    1.0       1.0  100.000000
3    Restaurante  162.0     840.0   19.285714
4          Total  186.0     867.0   21.453287

# segment detailed analysis

In [31]:
def term_analysis_region_detailed(df, region='', term='long'):
    """Return the dataframe specified by each reasons for long and short term user"""
    reasons = pd.DataFrame({'razon': input_df['razon'].unique(), 'Comercio':0, 'Institución':0, 'Restaurante':0})
    
    df = df[df['segmento'] != 'CNPJ Invalido']
    if region:
        df = df[df['region']==region]
        
    term_df = pd.pivot_table(df[df['term']==term], values='uid', index=['razon'], columns=['segmento'], aggfunc='count').reset_index()
    term_df = pd.concat([term_df, reasons]).groupby('razon').sum().reset_index()
    term_df = term_df[term_df['razon'] != 'sin motivo']
    term_df.fillna(0, inplace=True)
    term_df.rename(columns={
        'Comercio': 'Comercio_{}'.format(term),  
        'Institución': 'Institución_{}'.format(term), 
        'Restaurante': 'Restaurante_{}'.format(term)}, inplace=True)
    return term_df

In [32]:
def total_analysis_region_detailed(df, region=''):
    long = term_analysis_region_detailed(df, region=region, term='long')
    short = term_analysis_region_detailed(df, region=region, term='short')
    result = pd.concat([long, short[['Comercio_short', 'Institución_short', 'Restaurante_short']]], axis=1)
    return result

In [33]:
total_analysis_region_detailed(input_df)

,razon,Comercio_long,Institución_long,Restaurante_long,Comercio_short,Institución_short,Restaurante_short
0,Actualmente compra al día,0.0,0.0,92.0,0.0,1.0,131.0
1,Contaminado / Descompuesto (Podrido),0.0,0.0,6.0,0.0,0.0,5.0
2,Creo una cuenta nueva,0.0,0.0,6.0,1.0,0.0,3.0
3,Descuento o promoción no aplicado / mal calculado,0.0,0.0,1.0,0.0,0.0,4.0
4,El horario de entrega de la mañana es muy útil...,0.0,0.0,1.0,0.0,0.0,0.0
5,Eles entregaram fora do horário,0.0,0.0,0.0,0.0,0.0,2.0
6,Faixas de entrega não funcionam para mim,0.0,0.0,0.0,0.0,0.0,3.0
7,Golpeado,0.0,0.0,1.0,0.0,0.0,4.0
8,Maduración incorrecta (verde o sobremaduro),0.0,0.0,1.0,0.0,0.0,8.0
9,Mala atención del conductor,0.0,0.0,6.0,0.0,0.0,10.0
10,Mala atención del hunter,0.0,0.0,1.0,0.0,0.0,5.0
11,Me entregaron producto equivocado,0.0,0.0,1.0,0.0,0.0,3.0
12,Necesita de credito,0.0,0.0,55.0,0.0,0.0,64.0
13,No sabe usar la app,0.0,0.0,0.0,0.0,0.0,3.0
14,Orden no llega a pedido mínimo,1.0,0.0,159.0,5.0,0.0,180.0
15,Parte de mi pedido no llegó,0.0,0.0,7.0,0.0,0.0,5.0
16,Pedido nunca llegó,0.0,0.0,3.0,0.0,0.0,5.0
17,Precios no competitivos,2.0,0.0,70.0,0.0,1.0,99.0
18,Prefiero una hora de entrega especifica,0.0,0.0,4.0,0.0,0.0,5.0
19,Problema con Boleto,0.0,0.0,4.0,0.0,0.0,4.0
20,Problema con app Frubana,0.0,0.0,10.0,0.0,0.0,7.0
21,Productos Agotados,1.0,0.0,16.0,1.0,0.0,15.0
22,Servicio al cliente,2.0,0.0,16.0,0.0,2.0,20.0
23,Tamaño erróneo (pequeño o grande),0.0,0.0,4.0,0.0,0.0,6.0
24,Tuvo un problema y no lo supo reportar,1.0,0.0,21.0,0.0,0.0,30.0

In [75]:
total_analysis_region_detailed(input_df,'BOG')

,razon,Comercio_long,Institución_long,Restaurante_long,Comercio_short,Institución_short,Restaurante_short
0,Actualmente compra al día,0.0,0.0,20.0,0.0,1.0,26.0
1,Contaminado / Descompuesto (Podrido),0.0,0.0,2.0,0.0,0.0,1.0
2,Creo una cuenta nueva,0.0,0.0,1.0,0.0,0.0,0.0
3,Descuento o promoción no aplicado / mal calculado,0.0,0.0,0.0,0.0,0.0,3.0
4,El horario de entrega de la mañana es muy útil...,0.0,0.0,0.0,0.0,0.0,0.0
5,Eles entregaram fora do horário,0.0,0.0,0.0,0.0,0.0,0.0
6,Faixas de entrega não funcionam para mim,0.0,0.0,0.0,0.0,0.0,0.0
7,Golpeado,0.0,0.0,1.0,0.0,0.0,1.0
8,Maduración incorrecta (verde o sobremaduro),0.0,0.0,0.0,0.0,0.0,2.0
9,Mala atención del conductor,0.0,0.0,2.0,0.0,0.0,1.0
10,Mala atención del hunter,0.0,0.0,0.0,0.0,0.0,2.0
11,Me entregaron producto equivocado,0.0,0.0,0.0,0.0,0.0,1.0
12,Necesita de credito,0.0,0.0,0.0,0.0,0.0,0.0
13,No sabe usar la app,0.0,0.0,0.0,0.0,0.0,0.0
14,Orden no llega a pedido mínimo,0.0,0.0,7.0,0.0,0.0,4.0
15,Parte de mi pedido no llegó,0.0,0.0,3.0,0.0,0.0,0.0
16,Pedido nunca llegó,0.0,0.0,0.0,0.0,0.0,1.0
17,Precios no competitivos,0.0,0.0,27.0,0.0,1.0,33.0
18,Prefiero una hora de entrega especifica,0.0,0.0,1.0,0.0,0.0,0.0
19,Problema con Boleto,0.0,0.0,0.0,0.0,0.0,0.0
20,Problema con app Frubana,0.0,0.0,4.0,0.0,0.0,4.0
21,Productos Agotados,0.0,0.0,3.0,0.0,0.0,2.0
22,Servicio al cliente,0.0,0.0,5.0,0.0,2.0,9.0
23,Tamaño erróneo (pequeño o grande),0.0,0.0,0.0,0.0,0.0,3.0
24,Tuvo un problema y no lo supo reportar,0.0,0.0,1.0,0.0,0.0,1.0

In [34]:
def define_quantiles(df, region=''):
    if region:
        df = df[df['region'] == region]
    
    quantiles = [
        df['subtotal'].quantile(0.25),
        df['subtotal'].quantile(0.5),
        df['subtotal'].quantile(0.75),
        df['subtotal'].quantile(1),
    ]
    
    return quantiles

In [35]:
def quantiles_analysis(df, cities):
    data = {}
    data['GLOBAL'] = define_quantiles(df)
    for city in cities:
        data[city] =  define_quantiles(df, city)
    
    return pd.DataFrame(data, index=['Q1','Q2','Q3','Q4'])

In [36]:
quantiles_analysis(last_month_details, cities)

,GLOBAL,BOG,BAQ,CMX,GDL,SPO,BHZ
Q1,77.443460,99.595145,93.219303,53.138093,49.580511,95.537371,63.701031
Q2,173.168838,212.221243,200.072148,116.119072,106.073997,227.021907,194.791237
Q3,370.756378,413.181498,391.589820,239.497916,223.577905,522.329253,436.362113
Q4,109898.993226,75554.834000,104768.878513,109898.993226,12589.757165,25388.951031,3369.061856

In [37]:
def segment_quantile_analysis(present_df, past_df, city=''):
    if city:
        present_df = present_df[present_df['region']==city]
        past_df = past_df[past_df['region']==city]
    
    present_resume = present_df.groupby(['segmento'])['uid'].count().reset_index()
    past_resume =  past_df.groupby(['segmento']).count().reset_index().rename(columns={'segmento':'segmento_past', 'uid':'uid_past'})
    
    result = pd.concat([present_resume, past_resume], axis=1)[['segmento', 'uid', 'uid_past']]
    result = result.append(result.sum(numeric_only=True), ignore_index=True)
    result['%'] = result['uid']/result['uid_past'] * 100
    result['segmento'].fillna('Total', inplace=True)
    return  result

In [39]:
def quantile_assign(value, quantiles):
    if value <= quantiles[0]:
        return '0 - Q1'
    elif value > quantiles[0] and value <= quantiles[1]:
        return 'Q1 - Q2'
    elif value > quantiles[1] and value <= quantiles[2]:
        return 'Q2 - Q3'
    else:
        return 'Q3 - Q4'

In [40]:
input_df['subtotal'].apply(quantile_assign, quantiles=define_quantiles(last_month_details)).value_counts()

0 - Q1     5465
Q1 - Q2    3016
Q2 - Q3    1527
Q3 - Q4     667
Name: subtotal, dtype: int64

In [41]:
last_month_details['subtotal'].apply(quantile_assign, quantiles=define_quantiles(last_month_details)).value_counts()

0 - Q1     14691
Q3 - Q4    14658
Q2 - Q3    14657
Q1 - Q2    14625
Name: subtotal, dtype: int64

In [65]:
def quantile_segment_analysis(present_df, past_df, city=''):
    if city:
        present_df = present_df[present_df['region'] == city]
        past_df = past_df[past_df['region']== city ]
        
    actual = present_df['subtotal'].apply(quantile_assign, quantiles=define_quantiles(past_df, city)).value_counts()
    past = past_df['subtotal'].apply(quantile_assign, quantiles=define_quantiles(past_df, city)).value_counts()
    result = pd.concat([actual, past], axis=1)
    result = result.append(result.sum(numeric_only=True), ignore_index=True)
    result['%'] =result.iloc[:,0]/result.iloc[:,1] * 100
    result = result.rename(index={0:'0 - Q1', 1:'Q1 - Q2', 2:'Q2 - Q3', 3:'Q3 - Q4', 4:'Total'})
    return result

In [66]:
quantile_segment_analysis(input_df, last_month_details)

         subtotal  subtotal          %
0 - Q1       5465     14691  37.199646
Q1 - Q2      3016     14625  20.622222
Q2 - Q3      1527     14657  10.418230
Q3 - Q4       667     14658   4.550416
Total       10675     58631  18.207092

In [70]:
quantile_segment_analysis(input_df, last_month_details, 'BOG')

         subtotal  subtotal          %
0 - Q1       1308      4142  31.578947
Q1 - Q2       643      4141  15.527650
Q2 - Q3       322      4141   7.775900
Q3 - Q4       205      4142   4.949300
Total        2478     16566  14.958348

In [71]:
quantile_segment_analysis(input_df, last_month_details, 'BAQ')

         subtotal  subtotal          %
0 - Q1        332      1260  26.349206
Q1 - Q2       172      1259  13.661636
Q2 - Q3       100      1259   7.942812
Q3 - Q4        54      1260   4.285714
Total         658      5038  13.060738

In [72]:
quantile_segment_analysis(input_df, last_month_details, 'CMX')

         subtotal  subtotal          %
0 - Q1       1701      3961  42.943701
Q1 - Q2      1115      3957  28.177913
Q2 - Q3       642      3959  16.216216
Q3 - Q4       228      3959   5.759030
Total        3686     15836  23.276080

In [73]:
quantile_segment_analysis(input_df, last_month_details, 'SPO')

         subtotal  subtotal          %
0 - Q1       1501      4103  36.582988
Q1 - Q2       772      4102  18.820088
Q2 - Q3       359      4102   8.751828
Q3 - Q4       138      4103   3.363393
Total        2770     16410  16.879951

In [74]:
quantile_segment_analysis(input_df, last_month_details, 'BHZ')

         subtotal  subtotal          %
0 - Q1         94       217  43.317972
Q1 - Q2        55       217  25.345622
Q2 - Q3        24       216  11.111111
Q3 - Q4        13       217   5.990783
Total         186       867  21.453287